# cloudbuild.yaml
# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml
#

steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--tag=gcr.io/$PROJECT_ID/cloudbuild:android-builder'
  - '.'
  waitFor: ['-']
  
images:
- 'gcr.io/$PROJECT_ID/cloudbuild:android-builder'

